packages:
  - 'docs'
  - 'packages/components'
  - 'packages/crane'
  - 'packages/grid'
  - 'packages/icons'
  - 'packages/layout'
  - 'packages/test'
  - 'packages/themes'
  - 'packages/typography'
  - 'packages/typewriter'
  - 'examples/angular'
  - 'examples/react'
  - 'examples/vue'

catalog:
  '@web/dev-server': 0.4.6
  '@web/dev-server-esbuild': 1.0.3
  '@web/dev-server-rollup': 0.6.4
  '@web/test-runner': 0.19.0
  '@web/test-runner-core': 0.13.4
  '@web/test-runner-playwright': 0.11.0
  '@web/test-runner-visual-regression': 0.10.0
  custom-element-types: 0.2.7
  del-cli: 6.0.0
  lit: ^3.2.1
  tslib: ^2.8.1
  typescript: 5.6.3
  vite: 5.4.11
  modern-normalize: ^3.0.1
  playwright: 1.48.2
  publint: 0.2.12