name: Deploy Docs
on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version-file: './.nvmrc'
          cache: 'npm'
      - uses: google/wireit@setup-github-actions-caching/v1
      - run: npm ci
      - run: cd docs && npm run ci
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITES_FC2CF }}'
          channelId: live
          projectId: sites-fc2cf
          entryPoint: ./docs