name: Build and Preview
on: pull_request

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - uses: google/wireit@setup-github-actions-caching/v2
      - run: npm run setup
      - run: npm run ci
      - if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITES_FC2CF }}'
          projectId: sites-fc2cf
          entryPoint: ./docs
