name: Build and Preview
on: pull_request

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: './.nvmrc'
          cache: 'npm'
      - uses: google/wireit@setup-github-actions-caching/v1
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run ci
      # - uses: actions/upload-artifact@v3
      #   if: always()
      #   with:
      #     name: components-visual-report
      #     path: packages/components/screenshots/
      #     retention-days: 30
      - if: '${{ github.event.pull_request.head.repo.full_name == github.repository }}'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_SITES_FC2CF }}'
          projectId: sites-fc2cf
          entryPoint: ./docs
