name: Release
on:
  push:
    branches:
      - main

jobs:
  release:
    name: Release
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version-file: './.nvmrc'
          cache: 'npm'
      - uses: google/wireit@setup-github-actions-caching/v1
      - run: npm install -g npm@latest
      - run: npm ci
      - run: npx playwright install --with-deps chromium
      - run: npm run ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
          NPM_CONFIG_PROVENANCE: true
        run: npx semantic-release
